import { auth } from '@clerk/nextjs/server'
import { createServiceClient } from '@/lib/supabase/service'
import BentoGrid from '@/components/bento/BentoGrid'
import { AboutTile } from '@/components/about/AboutMapTile'
import EventsTile from '@/app/(dashboard)/components/tiles/EventsTile'
import ProfileTile from '@/app/(dashboard)/components/tiles/ProfileTile'
import GuidesTile from '@/app/(dashboard)/components/tiles/GuidesTile'
import LocationTile from '@/app/(dashboard)/components/tiles/LocationTileLazy'
import ThemeTile from '@/app/(dashboard)/components/tiles/ThemeTile'
import SocialsTile from '@/app/(dashboard)/components/tiles/SocialsTile'
import TripsTile from '@/app/(dashboard)/components/tiles/TripsTile'
import AnnouncementsTile from '@/app/(dashboard)/components/tiles/AnnouncementsTile'
import LinksTile from '@/app/(dashboard)/components/tiles/LinksTile'
